.\"
.\" mate-file-share-properties manual page.
.\" (C) 2013 Scott Balneaves (sbalneav@mate-desktop.org)
.\"
.TH MATE-FILE-SHARE-PROPERTIES 1 "MATE"
.SH NAME
mate-file-share-properties \- Edit MATE file sharing properties.
.SH SYNOPSIS
.B mate-file-share-properties
.SH DESCRIPTION
The \fImate-file-share-properties\fP program allows you to turn on and off sharing of public files, as well as enabling or disabling Bluetooth filesharing.
desktop.
.SH BUGS
If you find bugs in the \fIeom\fP program, please report
these on https://github.com/mate-desktop/mate-user-share/issues.
