##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-user-share
    - caja
    - dbus-glib
    - gcc
    - git
    - intltool
    - itstool
    - libcanberra
    - libnotify
    - make
    - mate-common
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-user-share
    - git
    - intltool
    - libcaja-extension-dev
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libnotify-dev
    - libselinux1-dev
    - libxt-dev
    - make
    - mate-common
    - pkg-config
    - quilt
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-user-share.git
    - caja-devel
    - dbus-glib-devel
    - desktop-file-utils
    - gcc
    - git
    - gtk2-devel
    - httpd
    - libICE-devel
    - libSM-devel
    - libcanberra-devel
    - libnotify-devel
    - libselinux-devel
    - make
    - mate-common
    - redhat-rpm-config
    - yelp-tools

  ubuntu:
    - git
    - intltool
    - libcaja-extension-dev
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libnotify-dev
    - libselinux1-dev
    - libxt-dev
    - make
    - mate-common
    - pkg-config
    - quilt
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-user-share-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
